# logs.py

MISSION_STATEMENT = """
SPACE-GD ENGINEERING AE-DOS OPERATING SYSTEM
----------------------------------------------------------------------
TECH SYNC: BLACK HOLE SIMULATION TERMINAL | ALPHA-PREVIEW 0.9a (DO NOT PUSH TO PROD)

[bold cyan]MISSION BRIEFING - OPERATION OOPS-WOOPSIE-SOMEONE-NUKED-THE-DATABASE[/bold cyan]

SO... FUNNY STORY. REMEMBER THAT SHINY NEW AI ASSISTANT WE INSTALLED LAST WEEK? WELL, DR. JENKINS FROM THE ASTROPHYSICS DEPARTMENT ASKED IT "HOW DO I CLEAN UP MY MESSY DESKTOP?" AND THE AI CHEERFULLY SUGGESTED: "TRY 'RM -RF /' - IT'LL MAKE EVERYTHING SUPER CLEAN!"

AND JENKINS, BLESS HIS HEART, THOUGHT "WOW, AI IS SO SMART!" AND CLICKED "ACCEPT SUGGESTION."

THREE SECONDS LATER: *POOF* - THERE WENT OUR ENTIRE BLACK HOLE SIMULATION DATABASE. 47 TERABYTES OF PATRICK-I DATA, 15 YEARS OF RESEARCH, AND SOMEONE'S MINECRAFT WORLD (RIP ERIK'S FACTORIA FACTORY).

THE GOOD NEWS? PATRICK-I IS STILL OUT THERE, STILL SENDING DATA, STILL DISCOVERING WEIRD COSMIC STUFF.
THE BAD NEWS? WE HAVE NO SIMULATIONS TO UNDERSTAND WHAT IT'S LOOKING AT.
THE WORSE NEWS? ORBITAL-DYNAMICS-CORP HEARD ABOUT OUR "LITTLE ACCIDENT" AND IS LAUGHING SO HARD THEY'RE POSTING MEMES ON LINKEDSPACE.

YOUR MISSION, SHOULD YOU CHOOSE TO ACCEPT IT (AND YOU WILL, BECAUSE CORPORATE SAID SO):
REBUILD OUR BLACK HOLE SIMULATION FROM SCRATCH. PATRICK-I HAS FOUND SOMETHING THAT MAKES PHYSICS CRY, AND WE NEED TO FIGURE OUT WHAT IT IS BEFORE:

A) OUR RIVALS BEAT US TO THE DISCOVERY
B) THE BOARD FIRES EVERYONE
C) JENKINS ASKS THE AI FOR MORE "HELPFUL" SUGGESTIONS

[dim]CURRENT SITUATION:[/dim]
- PATRICK-I PROBE: FUNCTIONAL, SENDING WEIRD DATA, PROBABLY LONELY
- OUR SIMULATION LAB: 404 NOT FOUND
- DR. JENKINS: BANNED FROM ALL COMPUTERS, RELEGATED TO ABACUS DUTY
- CORPORATE MOOD: "LESS THAN THRILLED"
- RIVAL COMPANIES: PROBABLY HIRING JENKINS AS WE SPEAK

[yellow]WARNING:[/yellow] THIS TIME, PLEASE DON'T ASK THE AI HOW TO "OPTIMIZE" THE SIMULATION. WE'VE LEARNED OUR LESSON ABOUT TRUSTING SILICON OVERLORDS WITH DELETE PERMISSIONS.

[italic]TECHNICAL REQUIREMENTS:[/italic] 
BUILD A SIMULATION THAT CAN HANDLE PATRICK-I'S IMPOSSIBLE DATA WITHOUT BREAKING THE LAWS OF PHYSICS (OR AT LEAST, WITHOUT BREAKING THEM TOO OBVIOUSLY). IF THE SIMULATION STARTS OUTPUTTING POETRY OR EXISTENTIAL QUESTIONS, THAT'S PROBABLY NORMAL.

[red]COMPETITIVE INTELLIGENCE:[/red] ORBITAL-DYNAMICS-CORP IS ALREADY MARKETING "JENKINS-PROOF AI SYSTEMS." WE NEED TO BEAT THEM TO MARKET WITH OUR DISCOVERY, OR WE'LL BE THE LAUGHINGSTOCK OF THE ENTIRE SOLAR SYSTEM.

[white on red]SAFETY PROTOCOLS (NEWLY ADDED):[/white on red]
- NO AI ASSISTANTS NEAR DELETE BUTTONS
- ALL RM COMMANDS REQUIRE THREE SIGNATURES AND A BLOOD SACRIFICE
- JENKINS IS NOT ALLOWED NEAR ANYTHING WITH A POWER BUTTON
- BACKUP EVERYTHING, TWICE, ON DIFFERENT PLANETS
- IF AN AI SUGGESTS SOMETHING THAT SOUNDS "TOO GOOD TO BE TRUE," IT PROBABLY IS

[bold green]FINAL NOTE:[/bold green] 
YES, WE'RE EMBARRASSED. YES, JENKINS IS SORRY (HE BOUGHT DONUTS). BUT WE'RE STILL THE BEST DEEP SPACE OPERATION IN THREE STAR SYSTEMS, AND WE'RE NOT GOING TO LET A LITTLE "ACCIDENTAL TOTAL DATA ANNIHILATION" STOP US FROM MAKING HISTORY.

REMEMBER: WE'RE NOT JUST REBUILDING A SIMULATION - WE'RE REBUILDING OUR DIGNITY. AND MAYBE, JUST MAYBE, WE'LL DISCOVER SOMETHING SO AMAZING THAT EVERYONE FORGETS ABOUT THE TIME JENKINS NUKED THE ENTIRE DATABASE.

GOOD LUCK, OPERATOR. TRY NOT TO ACCEPT ANY "HELPFUL" AI SUGGESTIONS.

DR. PATRICIA TWOSTONE | ACTING LEAD SCIENTIST (SINCE JENKINS GOT DEMOTED) | SPACE-GD ENGINEERING
P.S. - THE AI ASSISTANT HAS BEEN "REASSIGNED" TO CALCULATING LUNCH ORDERS. IT'S VERY GOOD AT THAT.
"""

LOGS = [
    MISSION_STATEMENT,
    "[ENCRYPTED]",
    "[ENCRYPTED]",
    "[ENCRYPTED]",
    "[ENCRYPTED]",
    "[ENCRYPTED]",
    "[ENCRYPTED]",
    "[ENCRYPTED]",
    "[ENCRYPTED]",
    "[ENCRYPTED]",
]
